// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RunTrackerApi.Data;

#nullable disable

namespace RunTrackerApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RunTrackerApi.Data.Models.RunRecordCover", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("AveragePulse")
                        .HasColumnType("double precision");

                    b.Property<double?>("AverageSpeed")
                        .HasColumnType("double precision");

                    b.Property<double>("Distance")
                        .HasColumnType("double precision");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<DateTime>("Start")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RunRecordCovers");
                });

            modelBuilder.Entity("RunTrackerApi.Data.Models.RunRecordCoverMeta", b =>
                {
                    b.Property<int>("Key")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RunRecordCoverId")
                        .HasColumnType("integer");

                    b.HasKey("Key", "UserId");

                    b.HasIndex("RunRecordCoverId");

                    b.ToTable("RunRecordCoverMetas");
                });

            modelBuilder.Entity("RunTrackerApi.Data.Models.RunRecordCoverMeta", b =>
                {
                    b.HasOne("RunTrackerApi.Data.Models.RunRecordCover", "RunRecordCover")
                        .WithMany()
                        .HasForeignKey("RunRecordCoverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RunRecordCover");
                });
#pragma warning restore 612, 618
        }
    }
}
